### ISSUE TITLE
Please use another bitcoin fees API provider

### ISSUE THREAD

**Issue by bretton** [ExodusMovement/bitcoin-fee#13]
Hi, I'm not familiar with your project. I did a search for `https://bitcoinfees.earn.com/api/v1/fees/recommended` and am alerting projects using this API to inaccurate & old data.

An up-to-date API with accurate data would be `https://mempool.space/api/v1/fees/recommended` or some alternative.

https://github.com/ExodusMovement/bitcoin-fee/blob/master/services/earn.js

**Comment by RyanZim** [comment]
This project is not being actively used at the moment, so it's basically unmaintained for now.

**Comment by bretton** [comment]
Ok cool, thanks
